In [7]:
import pandas as pd
df = pd.read_csv("../dataset/loan_approval_dataset.csv")

In [8]:
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [9]:
df.shape

df.columns

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

np.int64(0)

In [11]:
df.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03
mean,2135.000000,2.498712,5.059124e+06,1.513345e+07,10.900445,599.936051,7.472617e+06,4.973155e+06,1.512631e+07,4.976692e+06
std,1232.498479,1.695910,2.806840e+06,9.043363e+06,5.709187,172.430401,6.503637e+06,4.388966e+06,9.103754e+06,3.250185e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1068.000000,1.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2135.000000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3202.000000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

In [12]:
df.describe(include='object')

        education self_employed loan_status
count        4269          4269        4269
unique          2             2           2
top      Graduate           Yes    Approved
freq         2144          2150        2656

In [15]:
print(df.columns.tolist())

['loan_id', ' no_of_dependents', ' education', ' self_employed', ' income_annum', ' loan_amount', ' loan_term', ' cibil_score', ' residential_assets_value', ' commercial_assets_value', ' luxury_assets_value', ' bank_asset_value', ' loan_status']

In [16]:
df.columns = df.columns.str.strip()

In [17]:
print(df.columns.tolist())

['loan_id', 'no_of_dependents', 'education', 'self_employed', 'income_annum', 'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value', 'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value', 'loan_status']

In [18]:
df["income_annum"].describe()

count    4.269000e+03
mean     5.059124e+06
std      2.806840e+06
min      2.000000e+05
25%      2.700000e+06
50%      5.100000e+06
75%      7.500000e+06
max      9.900000e+06
Name: income_annum, dtype: float64

In [19]:
df["income_annum"].describe()

df.groupby("loan_status")["income_annum"].mean()

loan_status
Approved    5.025904e+06
Rejected    5.113825e+06
Name: income_annum, dtype: float64

In [20]:
df["loan_amount"].describe()

df["loan_amount"].value_counts().head()

loan_amount
10600000    27
20000000    24
9400000     24
23900000    23
16800000    23
Name: count, dtype: int64

In [21]:
pd.crosstab(df["education"], df["loan_status"])

loan_status   Approved  Rejected
education
Graduate          1339       805
Not Graduate      1317       808

In [22]:
df["cibil_score"].describe()

df.groupby("loan_status")["cibil_score"].mean()

loan_status
Approved    703.461973
Rejected    429.468072
Name: cibil_score, dtype: float64

In [23]:
df.to_csv("cleaned_loan_data.csv", index=False)

In [24]:
df["income_annum"].describe()

df.groupby("loan_status")["income_annum"].mean()

loan_status
Approved    5.025904e+06
Rejected    5.113825e+06
Name: income_annum, dtype: float64

In [25]:
df["loan_amount"].describe()

count    4.269000e+03
mean     1.513345e+07
std      9.043363e+06
min      3.000000e+05
25%      7.700000e+06
50%      1.450000e+07
75%      2.150000e+07
max      3.950000e+07
Name: loan_amount, dtype: float64

In [26]:
pd.crosstab(df["education"], df["loan_status"])

loan_status   Approved  Rejected
education
Graduate          1339       805
Not Graduate      1317       808

In [27]:
df.groupby("loan_status")["cibil_score"].mean()

loan_status
Approved    703.461973
Rejected    429.468072
Name: cibil_score, dtype: float64

In [28]:
df["loan_status"].value_counts()

loan_status
Approved    2656
Rejected    1613
Name: count, dtype: int64

In [29]:
df.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03
mean,2135.000000,2.498712,5.059124e+06,1.513345e+07,10.900445,599.936051,7.472617e+06,4.973155e+06,1.512631e+07,4.976692e+06
std,1232.498479,1.695910,2.806840e+06,9.043363e+06,5.709187,172.430401,6.503637e+06,4.388966e+06,9.103754e+06,3.250185e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1068.000000,1.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2135.000000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3202.000000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

In [30]:
summary = df.describe()

summary.to_csv("../reports/statistical_summary.csv")

In [31]:
insights = """
LOAN APPROVAL & BANKING ANALYSIS - BUSINESS INSIGHTS

1. Dataset Overview:
- Total loan applications analyzed: 4269
- The dataset contains applicant income, loan amount, credit score, education,
  employment status, assets, and loan approval status.

2. Loan Approval Analysis:
- Approved loans: 2656
- Rejected loans: 1613
- Overall loan approval rate: approximately 62.22%

3. Income Analysis:
- Applicant income varies significantly across customers.
- Higher income applicants generally receive higher loan amounts.

4. Loan Amount Analysis:
- Loan amounts show variation based on applicant financial profile.
- Some applicants have significantly higher loan requirements.

5. Education Analysis:
- Education level affects loan approval patterns.
- Graduates show different approval trends compared to non-graduates.

6. Credit Score Analysis:
- CIBIL score is an important factor in loan approval decisions.
- Applicants with stronger credit scores are more likely to receive approval.

7. Property & Asset Analysis:
- Applicant assets help understand financial stability.
- Asset ownership can support better loan eligibility decisions.

8. Business Recommendations:
- Use credit score-based risk assessment.
- Review high-income applicants for higher-value loan opportunities.
- Improve approval decisions using applicant financial indicators.
- Monitor rejected applications to identify improvement areas.

Conclusion:
The analysis helps the financial institution improve loan approval decisions,
reduce risk, and identify potential customers.
"""

with open("../reports/business_insights_report.txt", "w") as file:
    file.write(insights)